import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import React from "react";

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Nippon Global Energy',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.variable}  antialiased`}>{children}</body>
		</html>
	);
}
