import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import '../globals.css'

import {ReactNode} from 'react'
import {NextIntlClientProvider} from 'next-intl'
import {getMessages} from 'next-intl/server'


const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Nippon Global Energy',
	description: 'Generated by create next app',
};

// type Props = {
// 	children: ReactNode;
// 	params: { locale: string }
// }

export default async function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	const messages = await getMessages()
	
	return (
		<NextIntlClientProvider messages={messages}>
			<html lang='en'>
				<body className={`${montserrat.variable} antialiased`}>
					{children}
				</body>
			</html>
		</NextIntlClientProvider>
	);
}
